version: '3.8'

services:
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
  postgres:
    image: "postgres:13.2-alpine"
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  mobili:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

volumes:
  postgres:
  cache:
    driver: local
      