version: '3.8'

services:
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes: 
      - cache:/data
  postgres:
    image: "postgres:13.2-alpine"
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db
  boiler:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - rabbitmq      

volumes:
  postgres:
  cache:
    driver: local
      